<?php

namespace AppBundle\Repository;

/**
 * AgreementTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgreementTimeRepository extends \Doctrine\ORM\EntityRepository
{
}
