<?php

namespace AppBundle\Repository;

/**
 * ProjectUserAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectUserAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
