<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProjectByUser($userId)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->join('p.user', 'f')
            ->where($qb->expr()->eq('f.id', $userId));
        return $qb->getQuery()->getResult();
    }
}
