<?php

namespace AppBundle\Repository;

/**
 * ProjectsUserAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsUserAssignmentRepository extends \Doctrine\ORM\EntityRepository
{
}
