<?php

namespace AppBundle\Repository;

/**
 * TimesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimesRepository extends \Doctrine\ORM\EntityRepository
{
}
