<?php

namespace AppBundle\Repository;

/**
 * TimerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimerRepository extends \Doctrine\ORM\EntityRepository
{
}
