<?php

namespace AppBundle\Repository;

/**
 * timerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class timerRepository extends \Doctrine\ORM\EntityRepository
{
}
