<?php

namespace AppBundle\Repository;

/**
 * UserTeamsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTeamsRepository extends \Doctrine\ORM\EntityRepository
{
}
